# remote_theme: pages-themes/midnight@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one
remote_theme: niklasbuschmann/contrast@v2.11

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-polyglot
  - jekyll-toc
  - jekyll-mermaid
  - jekyll_reading_time

title: "Afasari"
author: "Batiar Afas Rahmamulia"
description: "Software Engineer specializing in Backend Development | Go, TypeScript, and Rust enthusiast | JLPT N4, Topik 1, TOEIC Score 850"
url: "https://afasari.github.io"
baseurl: ""
permalink: /post/:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout
show_excerpts: true
show_frame: true
show_sidebar: false
show_minimal: false
sidebar_title: "Afasari"

# Menu
navigation:
  - { file: "index.md", title: Home, sidebaricon: home, icon: home }
  - { file: "posts.md", title: Blogs }
  - { file: "projects.md", title: Projects }
  - { file: "tags.md", title: Tags }
  - { file: "categories.md", title: Categories }
  - { file: "about.md", title: Links }

footer:
  - { title: Mail, icon: envelope, url: "mailto:batiar.rahmamulia@gmail.com" }
  - {
      title: LinkedIn,
      icon: linkedin,
      url: "https://linkedin.com/in/batiar-afas",
    }
  - { title: Github, icon: github, url: "https://github.com/afasari" }
  - { title: Subscribe, icon: rss, url: "/feed.xml" }

reading_time:
  second_plural: "sec" # default: seconds
  minute_singular: "min" # default: minute
  minute_plural: "min" # default: minutes

# Blog settings
paginate: 5
paginate_path: "/post/page:num/"

# SEO Improvements
twitter:
  username: afasari
  card: summary_large_image

social:
  name: Batiar Afas Rahmamulia
  links:
    - https://linkedin.com/in/batiar-afas
    - https://github.com/afasari

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/default-social.png
      author: "Batiar Afas Rahmamulia"
